# Generated by Django 3.1.7 on 2021-04-22 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarletUser',
            fields=[
                ('carletuser_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('isBanned', models.BooleanField(default=False)),
                ('isSuperadmin', models.BooleanField(default=False)),
                ('permanentBan', models.BooleanField(default=False)),
                ('isTempBan', models.BooleanField(default=False)),
                ('tempBan', models.DateField(blank=True, null=True)),
                ('rating_counter', models.PositiveIntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
