# Generated by Django 3.1.7 on 2021-03-30 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carlet_User',
            fields=[
                ('carletuser_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('isVerified', models.BooleanField()),
                ('isBanned', models.BooleanField()),
                ('isSuperadmin', models.BooleanField()),
                ('permanentBan', models.BooleanField()),
                ('tempBan', models.DateField(null=True)),
                ('wallet', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
