# Generated by Django 3.1.7 on 2021-04-22 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_picture1', models.ImageField(upload_to='vehicle_picture1/')),
                ('vehicle_picture2', models.ImageField(upload_to='vehicle_picture2/')),
                ('vehicle_picture3', models.ImageField(blank=True, null=True, upload_to='vehicle_picture3/')),
                ('vehicle_picture4', models.ImageField(blank=True, null=True, upload_to='vehicle_picture4/')),
                ('vehicle_picture5', models.ImageField(blank=True, null=True, upload_to='vehicle_picture5/')),
                ('daily_rate', models.PositiveIntegerField(default=0)),
                ('vehicle_isVerified', models.BooleanField(default=False)),
                ('vehicle_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('put_up_for_rent', models.BooleanField(default=True)),
                ('rating_counter', models.IntegerField(default=1)),
                ('license_plate', models.CharField(default='abcd', max_length=50)),
                ('vehicle_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_user', to='Carletapp.carletuser')),
            ],
        ),
    ]
