# Generated by Django 3.1.7 on 2021-04-02 18:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlet_user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='carlet_user',
            name='tempBan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vehicle_detail',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_photos1', models.ImageField(default='', upload_to='')),
                ('vehicle_photos2', models.ImageField(default=None, upload_to='')),
                ('vehicle_photos3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('vehicle_photos4', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('vehicle_photos5', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle_isverified', models.BooleanField(default=False)),
                ('vehicle_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carletapp.carlet_user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_document',
            fields=[
                ('vehicledoc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.vehicle_detail')),
                ('reg_papers', models.FileField(upload_to='')),
                ('insurance_papers', models.FileField(upload_to='')),
                ('tracker_papers', models.FileField(upload_to='')),
                ('tracker1_papers', models.FileField(upload_to='')),
                ('ownerdoc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carletapp.carlet_user')),
            ],
        ),
    ]
