# Generated by Django 3.1.7 on 2021-04-10 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0002_auto_20210410_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='Carletapp.carletuser')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_id', to='Carletapp.carletuser')),
                ('vehicle_trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carletapp.vehicledetail')),
            ],
        ),
    ]
