# Generated by Django 3.1.7 on 2021-04-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0002_vehicle_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Location',
            fields=[
                ('vehicleloc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicleloc_id', serialize=False, to='Carletapp.vehicle_detail')),
                ('vehicle_street_address', models.TextField(max_length=300)),
                ('vehicle_city', models.CharField(max_length=50)),
                ('vehicle_state', models.CharField(max_length=50)),
                ('vehicle_zip', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('vehicle_longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
        ),
    ]
