# Generated by Django 3.1.7 on 2021-03-31 17:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0002_remove_carlet_user_tempban'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlet_user',
            name='tempBan',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='carlet_user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
