# Generated by Django 3.1.7 on 2021-04-22 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0003_vehicledocument_vehiclelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NIC', models.CharField(max_length=13, unique=True)),
                ('NIC_picture', models.ImageField(blank=True, null=True, upload_to='nic_pictures/')),
                ('driver_license', models.CharField(max_length=50)),
                ('driver_license_picture', models.ImageField(blank=True, null=True, upload_to='license_pictures/')),
                ('account_number', models.CharField(max_length=24)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_doc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doc_id', to='Carletapp.carletuser')),
            ],
        ),
    ]
