# Generated by Django 3.1.7 on 2021-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0003_tripdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
