# Generated by Django 3.1.7 on 2021-04-22 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0004_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.carletuser')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='proof_of_payment/')),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('payment_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('booking_confirm', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_id', to='Carletapp.carletuser')),
                ('vehicle_trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carletapp.vehicledetail')),
            ],
        ),
    ]
