# Generated by Django 3.1.7 on 2021-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0004_auto_20210331_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlet_user',
            name='tempBan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
