# Generated by Django 3.1.7 on 2021-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0005_remove_tripdetail_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='put_up_for_rent',
            field=models.BooleanField(default=True),
        ),
    ]
