# Generated by Django 3.1.7 on 2021-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0005_auto_20210331_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.EmailField(max_length=100)),
            ],
        ),
    ]
