# Generated by Django 3.2 on 2021-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0006_vehicledetail_put_up_for_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetail',
            name='vehicle_user',
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='NIC_picture',
            field=models.ImageField(blank=True, null=True, upload_to='nic_pictures/'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='driver_license_picture',
            field=models.ImageField(blank=True, null=True, upload_to='license_pictures/'),
        ),
        migrations.DeleteModel(
            name='TripDetail',
        ),
        migrations.DeleteModel(
            name='VehicleDetail',
        ),
    ]
