# Generated by Django 3.1.7 on 2021-03-31 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0006_vehicle_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_city',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_name',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_state',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_street_address',
            field=models.TextField(default='nothing', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='vehicle_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
