# Generated by Django 3.1.7 on 2021-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0007_auto_20210411_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='NIC_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/nic_pictures/'),
        ),
    ]
