# Generated by Django 3.1.7 on 2021-04-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0008_vehicledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('vehicledoc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.vehicledetail')),
                ('reg_papers', models.FileField(upload_to='')),
                ('insurance_papers', models.FileField(upload_to='')),
                ('tracker_papers', models.FileField(upload_to='')),
            ],
        ),
    ]
