# Generated by Django 3.1.7 on 2021-04-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0008_vehicle_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Location',
            fields=[
                ('vehicleloc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.vehicle_detail')),
                ('vehicle_street_address', models.TextField(max_length=300)),
                ('vehicle_city', models.CharField(max_length=100)),
                ('vehicle_state', models.CharField(max_length=100)),
                ('vehicle_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('vehicle_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_city',
        ),
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_state',
        ),
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_street_address',
        ),
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_zip',
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_model',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_photos',
            field=models.ImageField(default='nothing', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_type',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_user_id',
            field=models.ForeignKey(default='nothing', on_delete=django.db.models.deletion.CASCADE, to='Carletapp.carlet_user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_document',
            name='insurance_papers',
            field=models.FileField(default='nothing', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_document',
            name='reg_papers',
            field=models.FileField(default='nothing', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_document',
            name='tracker_papers',
            field=models.FileField(default='nothing', upload_to=''),
            preserve_default=False,
        ),
    ]
