# Generated by Django 3.1.7 on 2021-04-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0009_auto_20210402_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='vehicle_photos',
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_photos1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_photos2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_photos3',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_photos4',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_photos5',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
