# Generated by Django 3.1.7 on 2021-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0009_auto_20210411_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='driver_license_picture',
            field=models.ImageField(blank=True, null=True, upload_to='license_pictures'),
        ),
    ]
