# Generated by Django 3.1.7 on 2021-04-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0011_auto_20210411_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('vehicleloc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicleloc_id', serialize=False, to='Carletapp.vehicledetail')),
                ('vehicle_street_address', models.TextField(blank=True, max_length=300, null=True)),
                ('vehicle_city', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_state', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_zip', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('vehicle_longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
        ),
    ]
