# Generated by Django 3.1.7 on 2021-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0011_auto_20210402_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_detail',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='vehicle_isverified',
            field=models.BooleanField(default=False),
        ),
    ]
