# Generated by Django 3.1.7 on 2021-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0012_carletuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='license_plate',
            field=models.CharField(default='abcd', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture1',
            field=models.ImageField(upload_to='vehicle_pictures1/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture2',
            field=models.ImageField(upload_to='vehicle_pictures2/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures3/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures4/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture5',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures5/'),
        ),
    ]
