# Generated by Django 3.1.7 on 2021-04-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0012_vehiclelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('vehicledoc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.vehicledetail')),
                ('reg_papers', models.ImageField(upload_to='')),
                ('insurance_papers', models.ImageField(upload_to='')),
                ('tracker_papers', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture1',
            field=models.ImageField(upload_to='vehicle_picture1/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture2',
            field=models.ImageField(upload_to='vehicle_picture2/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_picture3/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_picture4/'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_picture5',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_picture5/'),
        ),
    ]
