# Generated by Django 3.1.7 on 2021-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0013_auto_20210420_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='insurance_papers',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_papers/'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='reg_papers',
            field=models.ImageField(blank=True, null=True, upload_to='reg_papers/'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='tracker_papers',
            field=models.ImageField(blank=True, null=True, upload_to='tracker_papers/'),
        ),
    ]
