# Generated by Django 3.1.7 on 2021-04-19 15:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0013_auto_20210419_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='point_location',
            field=django.contrib.gis.db.models.fields.PointField(default=(0, 0), srid=4326, verbose_name='vehicle_location'),
        ),
    ]
