# Generated by Django 3.1.7 on 2021-04-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0014_vehiclelocation_point_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.carletuser')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='proof_of_payment/')),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('payment_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='carletuser',
            name='wallet',
        ),
        migrations.AddField(
            model_name='carletuser',
            name='rating_counter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='booking_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='rating_done_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='rating_done_renter',
            field=models.BooleanField(default=False),
        ),
    ]
