# Generated by Django 3.1.7 on 2021-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0016_auto_20210422_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='rating_done_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='rating_done_renter',
            field=models.BooleanField(default=False),
        ),
    ]
