# Generated by Django 3.1.7 on 2021-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0016_auto_20210423_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='vehicle_latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='vehicle_longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='vehicle_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='vehicle_zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
