# Generated by Django 3.1.7 on 2021-04-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0017_auto_20210423_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle_latitude',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle_longitude',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle_state',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle_zip',
        ),
    ]
