# Generated by Django 3.1.7 on 2021-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0018_auto_20210423_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_Redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='redeem_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
