# Generated by Django 3.1.7 on 2021-04-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0018_auto_20210423_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_Redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='redeem_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Carletapp.carletuser')),
                ('fav_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carletapp.vehicledetail')),
            ],
        ),
    ]
