# Generated by Django 3.1.7 on 2021-04-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carletapp', '0020_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'fav_vehicle')},
        ),
    ]
